/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanSearch: typeof import('vant/es')['Search']
    VirtualProjectTree: typeof import('./src/components/virtual-project-tree/virtual-project-tree.vue')['default']
    VirtualTree: typeof import('./src/components/virtual-project-tree/virtual-tree.vue')['default']
  }
}
